### ISSUE TITLE
compilation error when use library in project:  the trait bound `aws_sdk_cloudwatchlogs::Client: CloudWatchClient` is not satisfied 

### ISSUE THREAD

**Issue by edeustace** [ymgyt/tracing-cloudwatch#7]
I'm getting a compilation error when trying to use this crate in a bin project. The `Cargo.toml` and `src/main.rs` are below.

compilation error:

```shell
   Compiling demo-app v0.1.1 (tracing-cloudwatch-demo-app)
error[E0277]: the trait bound `aws_sdk_cloudwatchlogs::Client: CloudWatchClient` is not satisfied
  --> src\main.rs:14:17
   |
13 |             tracing_cloudwatch::layer().with_client(
   |                                         ----------- required by a bound introduced by this call
14 |                 cw_client,
   |                 ^^^^^^^^^ the trait `CloudWatchClient` is not implemented for `aws_sdk_cloudwatchlogs::Client`
   |
   = help: the following other types implement trait `CloudWatchClient`:
             aws_sdk_cloudwatchlogs::client::Client
             tracing_cloudwatch::client::NoopClient
note: required by a bound in `CloudWatchLayer::<S, D>::with_client`
  --> C:\Users\edeus\.cargo\registry\src\github.com-1ecc6299db9ec823\tracing-cloudwatch-0.1.1\src\layer.rs:62:17
   |
62 |         Client: CloudWatchClient + Send + Sync + 'static,
   |                 ^^^^^^^^^^^^^^^^ required by this bound in `CloudWatchLayer::<S, D>::with_client`

For more information about this error, try `rustc --explain E0277`.
```
Cargo.toml
```toml
[package]
name = "demo-app"
version = "0.1.1"
edition = "2021"


[dependencies]
tracing-cloudwatch = { version = "0.1.1", features = ["awssdk"] }
tokio = { version = "1.28", features = [
  "full",
  "rt",
  "sync",
  "time",
  "macros",
] }
tracing = { version = "0.1.35", default-features = false, features = ["std"] }
tracing-core = "0.1.30"
tracing-subscriber = { version = "0.3.17", default-features = false, features = [
  "std",
  "fmt",
  "smallvec",
] }
aws-config = "0.55.2"
aws-sdk-cloudwatchlogs = { version = "0.28.0" }
```

src/main.rs
```rust
use std::time::Duration;

use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

#[tokio::main]
async fn main() {
    let config = aws_config::load_from_env().await;

    let cw_client = aws_sdk_cloudwatchlogs::Client::new(&config);

    tracing_subscriber::registry::Registry::default()
        .with(
            tracing_cloudwatch::layer().with_client(
                cw_client,
                tracing_cloudwatch::ExportConfig::default()
                    .with_batch_size(5)
                    .with_interval(Duration::from_secs(1))
                    .with_log_group_name("tracing-cloudwatch")
                    .with_log_stream_name("stream-1"),
            ),
        )
        .init();
}
```

**Comment by merklefruit** [comment]
I'm having the exact same issue

**Comment by ymgyt** [comment]
Thank you for reporting the issue, I will work on a fix.

**Comment by ymgyt** [comment]
@edeustace @merklefruit 

A fixed version has been released as v0.1.2.

Please try the following

```toml
[dependencies]
tracing-cloudwatch = { version = "0.1.2", features = ["awssdk"] }
```

The cause of the problem was that I had increased the version of the aws sdk in dependabot, but had not released it.
The result was that the aws sdk trait targeted by tracing-cloudwatch and the user's trait were different.

If the problem persists, reopen this issue.
